language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

# Before install
before_install:
  - npm install coveralls

# Build script
script:
  - make ci
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls