language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.10"

# Before install
before_install:
  - npm install coveralls

# Build script
script:
  - make ci

# After successful build
after_success:
  - ./node_modules/coveralls/bin/coveralls.js